### PR TITLE
Add the global plate boundary model.

### PR DESCRIPTION
**Pull request by alarshi**
This PR adds the GWB files used for our global mantle flow models with a brief description. @tjhei @ljhwang etc: let me know your suggestions on how to improve the structure!

### CODE REVIEW

**Review by tjhei — COMMENTED** [review]
Awesome, thank you. Two things:
1. Can you create a ``models`` directory and put your files into ``models/Saxena2023``?
2. Would it be possible to have one .grid file for each .wb file with the same name?

**Comment by tjhei** [comment]
@MFraters do we want version 0.5 files or 0.6?

**Comment by alarshi** [comment]
Thank you for the suggestions! I addressed them in the latest commit.

**Comment by MFraters** [comment]
Let's do 0.6, because the visualization tool needs that and the input files should be compatible.

**Review by tjhei — APPROVED** [review]
Do you use the single grid file to visualize all 3 wb files?

**Comment by alarshi** [comment]
@tjhei : Yes, I forgot to reply to your comment. I have one `.grid` file to represent the Earth's upper mantle and different plate boundary models and the `gwb-grid` will create different `vtu` files corresponding to each of the plate boundary models for visualization. I can also make separate `.grid` files but they will be exact copies. Let me know what you want me to do!

**Comment by tjhei** [comment]
Yes, would you mind duplicating it?

**Comment by alarshi** [comment]
Got it! I added them in the recent commit.

**Review by tjhei — APPROVED** [review]

**Comment by MFraters** [comment]
The first model in the repository :tada: 
Thanks for setting this up @tjhei and @alarshi!

**Pull request merged**
